[package]
name = "hq"
version = "0.1.0"
authors = ["kappa0923 <tom.kappa0923@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "*"
